# Workflow to create manual
name: Create Manual

on:
  [push, pull_request]

jobs:
  export:
    name: Create Manual
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Generate
        uses: docker://pandoc/latex:3.1
        with:
          args: >-
            --defaults=manual/manual.yaml
            --output=manual.pdf

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: manual.pdf
